setwd("/Users/buckcrowley/Desktop/BDEL/BZDEL/meta_analysis/")

library(phylofactor)
library(grid)
library(gridBase)
library(stringi)
#source('R/other phylofactor scripts/fisherFactor.R')
source('R/taxonomy group name function.R')
source('R/bat filo and hnv sampling phylogeny update.R')
#source('R/other phylofactor scripts/visualization_fcns.R')
library(tidyverse)
library(taxize)

#..............obtain a couple more outcome variables..................................
load('data/bat_taxonomy_data.Rdata') 

load(file='data/seroprevalence.Rdata')
seroprevalence_filo_binary <- seroprevalence %>%
  mutate(seroprevalence_percentage_cat = ifelse(seroprevalence_percentage == 0, 0, 1)) %>%
  filter(!(is.na(species))) %>%
  dplyr::group_by(species, virus, seroprevalence_percentage_cat) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  filter(virus == 'Filovirus') %>%
  spread(seroprevalence_percentage_cat, count) %>%
  mutate(filovirus_positive_cat  = ifelse(is.na(`1`) & !is.na(`0`), 0,
                                          ifelse(!is.na(`1`), 1, NA))) %>%
  dplyr::select(c(species, filovirus_positive_cat)) %>%
  unique()

batphy1 <- left_join(batphy1, seroprevalence_filo_binary) 

seroprevalence_hnv_binary <- seroprevalence %>%
  mutate(seroprevalence_percentage_cat = ifelse(seroprevalence_percentage == 0, 0, 1)) %>%
  filter(!(is.na(species))) %>%
  dplyr::group_by(species, virus, seroprevalence_percentage_cat) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  filter(virus == 'Henipavirus') %>%
  spread(seroprevalence_percentage_cat, count) %>%
  mutate(henipavirus_positive_cat  = ifelse(is.na(`1`) & !is.na(`0`), 0,
                                            ifelse(!is.na(`1`), 1, NA))) %>%
  dplyr::select(c(species, henipavirus_positive_cat)) %>%
  unique()

batphy1 <- left_join(batphy1, seroprevalence_hnv_binary) 

  
#..................which african bats have been sampled for filoviruses

#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.......................okay going to filter out the results for which we dont have taxonomies
#.......................but really we shouldn't do this and need to figure out the missing taxonomies 

batphy1.africa <- dplyr::filter(batphy1, region == 'Africa') 
batphy1.africa<-batphy1.africa %>%
  mutate(index = row.names(batphy1.africa))
taxonomy_africa<- batphy1.africa[,c('species','tax')]


Z <- batphy1.africa$filo_surv

n_factors.africa = 10

pf.africa.filo <- phylofactor::twoSampleFactor(Z, africa_tree, method='Fisher', n_factors.africa ,ncores = 1)


#.................................................................................................
#.................................................................................................
#.................................................................................................
#.............................obtain names........................................................

nms.africa.filo <- list()
  
for (i in 2:length(pf.africa.filo$bins))
{
  indexes = pf.africa.filo$bins[[i]]
  species <- gsub("_", " ", tolower(africa_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy_africa[match(species,taxonomy_africa[,1]),2])
  
  nms.africa.filo[i] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))

  print(i)
}
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#......................END: alex's slack suggestion...............................................

B.africa.phylo <- bins(pf.africa.filo$basis[,1:n_factors.africa])
B.africa.phylo <- B.africa.phylo[2:n_factors.africa] 
nms.africa.filo1 <- nms.africa.filo[2:(n_factors.africa+1)]

## remove paraphyletic bin

probs.africa.phylo <- sapply(B.africa.phylo,FUN=function(ix,Z) mean(Z[ix]),Z=Z) %>% signif(.,digits=2)
names(nms.africa.filo1) <- probs.africa.phylo

#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#...............Null Simulation..........................................................

# null_simulations.africa.filo <- pf.nullsim(pf.africa.filo, reps = 100, nfactors = n_factors.africa, output ='pvals')
# 
# #nfactors <- pf$nfactors
# obs <- data.frame('Pvals'=pf.africa.filo$pvals,
#                   'factor'=1:n_factors.africa
#                   )
# null_simulations_matrix.africa.filo<- matrix(0,100,n_factors.africa)
# for (i in 1:100)
# {
#   null_simulations_matrix.africa.filo[i,] <- null_simulations.africa.filo[[i]]$pvals
# }
# null_simulations_matrix.africa.filo <- as.data.frame(t(null_simulations_matrix.africa.filo))
# ddf.africa.filo <- cbind(obs,null_simulations_matrix.africa.filo)
# 
# ddf.africa.filo %>%
#   tidyr::gather(group, pvalue, c(1,3:102)) %>%
#   mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
#   ggplot() +
#   geom_line(aes(x = factor, y= log(pvalue), group = group, color = color))

#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
# The Plot ---------------------------------------------------------------

#............................define our colors....................................................
#.................................................................................................
#............................1:  Yangochiroptera....."#FF0000FF"..................................
#............................2:  Myotis.............."#FF9900FF"..................................
#............................3:  Miniopterus........."#CCFF00FF"..................................
#............................4:  Pteropodidae........"#33FF00FF"..................................
#............................5:  Emballonuroidea....."#00FF66FF"..................................
#............................6:  Rhinolophus........."#00FFFFFF"..................................
#............................7:  Pipistrellini......."#0066FFFF"..................................
#............................8:  Pteropus............"#3300FFFF"..................................
#............................9:  Pteropodidae........"#CC00FFFF".................................
#............................10: Scotophilus kuhlii.."#FF0099FF"..................................
#............................11: Eidolon............."#FF0099FF"..................................
#............................12: Hipposideros........"#00FF66FF"..................................
#............................13: C. perspicillata...."#00FFFFFF"..................................
#............................14: D. rotundus........."#00FFFFFF"..................................
#............................14: Carollia............"#00FFFFFF"..................................
#............................15: Vespertilionoidea..."#00FFFFFF"..................................

colfcn.africa.filo <- function(n) return(c("#CC00FFFF", "#00FFFFFF"))

pf.tree.africa.filo <- pf.tree(pf.africa.filo, factor = 1:2, lwd=1, color.fcn=colfcn.africa.filo, branch.length = "none")
pf.tree.africa.filo$ggplot +
  ggtree::geom_tippoint(size=10*Z,col='blue')  

Legend.africa.filo <- pf.tree.africa.filo$legend
Legend.africa.filo$names <- nms.africa.filo1[1:2]
P.africa.filo <- sapply(probs.africa.phylo,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.africa.filo$names <- mapply(paste,Legend.africa.filo$names,P.africa.filo[1:2])
plot.new()
plot.new()
legend('topleft',legend=Legend.africa.filo$names,fill=Legend.africa.filo$colors,cex=1)


#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#...............POSITIVE AFRICAN BATS................................................
#....................................................................................
#...............POSITIVE AFRICAN BATS................................................
#....................................................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................



n_factors.africa = 10

Z.filo.pos<- batphy1[,c('tree_species', 'filo_samps', 'filovirus_positive_cat')] 

Z.filo.pos1  <- Z.filo.pos %>%
  rename(Species = tree_species) %>%
  mutate(Species = as.character(Species)) %>%
  mutate(Sample =1) %>%
  filter(!(is.na(filovirus_positive_cat)))

dropped.tips.filo.drop.tips <- Z.filo.pos %>%
  rename(Species = tree_species) %>%
  filter((is.na(filovirus_positive_cat))) %>%
  mutate(Species = as.character(Species)) %>%
  select(Species) %>%
  as.vector()

bat_tree.filo.pos <- ape::drop.tip(bat_tree,dropped.tips.filo.drop.tips$Species)

pf.africa.filo.pos <- gpf(Z.filo.pos1,bat_tree.filo.pos,frmla=filovirus_positive_cat~filo_samps+phylo,nfactors=10,mStableAgg=F)

pf.tree(pf.filo_pos)

#.................................................................................................
#.................................................................................................
#.................................................................................................
#.............................obtain names........................................................

nms.africa.filo.pos <- list()

for (i in 2:length(pf.africa.filo.pos$bins))
{
  indexes = pf.africa.filo.pos$bins[[i]]
  species_x <- gsub("_", " ", tolower(africa_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy_africa[match(species_x,taxonomy_africa[,1]),2])
  
  nms.africa.filo.pos[i] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))
  
  p<-batphy1 %>%
    filter(tolower(species) %in% species_x) %>%
    group_by(filo_surv) %>%
    summarise(n = n()) 
  
  print(as.numeric(p[2,'n'] / (p[2,'n'] + p[1,'n'])))
  print(i)
}
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#......................END: alex's slack suggestion...............................................

B.africa.phylo.pos <- bins(pf.africa.filo.pos$basis[,1:n_factors.africa])
B.africa.phylo.pos <- B.africa.phylo.pos[2:n_factors.africa] 
nms.africa.filo1.pos <- nms.africa.filo.pos[2:(n_factors.africa+1)]

## remove paraphyletic bin

#probs.africa.phylo.pos <- sapply(B.africa.phylo.pos,FUN=function(ix,Z) mean(Z[ix]),Z=Z) %>% signif(.,digits=2)
#names(nms.africa.filo1.pos) <- probs.africa.phylo.pos

#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#...............Null Simulation..........................................................

# null_simulations.africa.filo.pos <- pf.nullsim(pf.africa.filo.pos, reps = 250, nfactors = n_factors.africa, output ='pvals')
# 
# #nfactors <- pf$nfactors
# obs.filo.africa.pos <- data.frame('Pvals'=pf.africa.filo.pos$pvals,'factor'=1:n_factors.africa)
# 
# null_simulations_matrix.africa.filo.pos<- matrix(0,250,n_factors.africa)
# for (i in 1:250)
# {
#   null_simulations_matrix.africa.filo.pos[i,] <- null_simulations.africa.filo.pos[[i]]$pvals
# }
# null_simulations_matrix.africa.filo.pos <- as.data.frame(t(null_simulations_matrix.africa.filo.pos))
# ddf.africa.filo.pos <- cbind(obs.filo.africa.pos,null_simulations_matrix.africa.filo.pos)
# 
# ddf.africa.filo.pos %>%
#   tidyr::gather(group, pvalue, c(1,3:202)) %>%
#   mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
#   ggplot() +
#   geom_line(aes(x = factor, y= log(pvalue), group = group, color = color)) +
#   scale_x_continuous(limits=c(1, 10), breaks = seq(1,10, by= 1))
# 
# x <- ddf.africa.filo.pos %>%
#   tidyr::gather(group, pvalue, c(1,3:202)) %>%
#   mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) 
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
# The Plot ---------------------------------------------------------------

#............................define our colors....................................................
#.................................................................................................
#............................1:  Yangochiroptera....."#FF0000FF"..................................
#............................2:  Myotis.............."#FF9900FF"..................................
#............................3:  Miniopterus........."#CCFF00FF"..................................
#............................4:  Pteropodidae........"#33FF00FF"..................................
#............................5:  Emballonuroidea....."#00FF66FF"..................................
#............................6:  Rhinolophus........."#00FFFFFF"..................................
#............................7:  Pipistrellini......."#0066FFFF"..................................
#............................8:  Pteropus............"#3300FFFF"..................................
#............................9:  Pteropodidae........"#CC00FFFF".................................
#............................10: Scotophilus kuhlii.."#FF0099FF"..................................
#............................11: Eidolon............."#FF0099FF"..................................
#............................12: Hipposideros........"#00FF66FF"..................................
#............................13: C. perspicillata...."#00FFFFFF"..................................
#............................14: D. rotundus........."#00FFFFFF"..................................
#............................14: Carollia............"#00FFFFFF"..................................
#............................15: Vespertilionoidea..."#00FFFFFF"..................................

colfcn.africa.filo.pos <- function(n) return(c("#CC00FFFF", "#00FFFFFF"))

pf.tree.africa.filo.pos <- pf.tree(pf.africa.filo.pos, factor = 10, lwd=1, branch.length = "none")
pf.tree.africa.filo.pos$ggplot +
  ggtree::geom_tippoint(size=10*Z.filo.pos1$filovirus_positive_cat,col='blue')  

Legend.africa.filo <- pf.tree.africa.filo$legend
Legend.africa.filo$names <- nms.africa.filo1[1:2]
P.africa.filo <- sapply(probs.africa.phylo,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.africa.filo$names <- mapply(paste,Legend.africa.filo$names,P.africa.filo[1:2])
plot.new()
plot.new()
legend('topleft',legend=Legend.africa.filo$names,fill=Legend.africa.filo$colors,cex=1)


