setwd("/Users/buckcrowley/Desktop/BDEL/BZDEL/meta_analysis/")

library(phylofactor)
library(grid)
library(gridBase)
library(stringi)
#source('R/other phylofactor scripts/fisherFactor.R')
source('R/taxonomy group name function.R')
source('R/bat filo and hnv sampling phylogeny update.R')
#source('R/other phylofactor scripts/visualization_fcns.R')
library(tidyverse)
library(taxize)

#..............obtain a couple more outcome variables..................................
load('data/bat_taxonomy_data.Rdata') 

load(file='data/seroprevalence.Rdata')
seroprevalence_filo_binary <- seroprevalence %>%
  mutate(seroprevalence_percentage_cat = ifelse(seroprevalence_percentage == 0, 0, 1)) %>%
  filter(!(is.na(species))) %>%
  dplyr::group_by(species, virus, seroprevalence_percentage_cat) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  filter(virus == 'Filovirus') %>%
  spread(seroprevalence_percentage_cat, count) %>%
  mutate(filovirus_positive_cat  = ifelse(is.na(`1`) & !is.na(`0`), 0,
                                          ifelse(!is.na(`1`), 1, NA))) %>%
  dplyr::select(c(species, filovirus_positive_cat)) %>%
  unique()

batphy1 <- left_join(batphy1, seroprevalence_filo_binary) 

seroprevalence_hnv_binary <- seroprevalence %>%
  mutate(seroprevalence_percentage_cat = ifelse(seroprevalence_percentage == 0, 0, 1)) %>%
  filter(!(is.na(species))) %>%
  dplyr::group_by(species, virus, seroprevalence_percentage_cat) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  filter(virus == 'Henipavirus') %>%
  spread(seroprevalence_percentage_cat, count) %>%
  mutate(henipavirus_positive_cat  = ifelse(is.na(`1`) & !is.na(`0`), 0,
                                            ifelse(!is.na(`1`), 1, NA))) %>%
  dplyr::select(c(species, henipavirus_positive_cat)) %>%
  unique()

batphy1 <- left_join(batphy1, seroprevalence_hnv_binary) 
#..................which african bats have been sampled for filoviruses

#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.......................okay going to filter out the results for which we dont have taxonomies
#.......................but really we shouldn't do this and need to figure out the missing taxonomies 

batphy1.africa <- dplyr::filter(batphy1, region == 'Africa') 
batphy1.africa<-batphy1.africa %>%
  mutate(index = row.names(batphy1.africa))
taxonomy_africa<- batphy1.africa[,c('species','tax')]


Z <- batphy1.africa$filo_surv

n_factors.africa = 10

pf.africa.filo <- phylofactor::twoSampleFactor(Z, africa_tree, method='Fisher', n_factors.africa ,ncores = 1)


#.................................................................................................
#.................................................................................................
#.................................................................................................
#.............................obtain names........................................................

nms.africa.filo <- list()
  
for (i in 2:length(pf.africa.filo$bins))
{
  indexes = pf.africa.filo$bins[[i]]
  species <- gsub("_", " ", tolower(africa_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy_africa[match(species,taxonomy_africa[,1]),2])
  
  nms.africa.filo[i] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))

  print(i)
}
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#......................END: alex's slack suggestion...............................................

B.africa.phylo <- bins(pf.africa.filo$basis[,1:n_factors.africa])
B.africa.phylo <- B.africa.phylo[2:n_factors.africa] 
nms.africa.filo1 <- nms.africa.filo[2:(n_factors.africa+1)]

## remove paraphyletic bin

probs.africa.phylo <- sapply(B.africa.phylo,FUN=function(ix,Z) mean(Z[ix]),Z=Z) %>% signif(.,digits=2)
names(nms.africa.filo1) <- probs.africa.phylo

#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#...............Null Simulation..........................................................

# null_simulations.africa.filo <- pf.nullsim(pf.africa.filo, reps = 100, nfactors = n_factors.africa, output ='pvals')
# 
# #nfactors <- pf$nfactors
# obs <- data.frame('Pvals'=pf.africa.filo$pvals,
#                   'factor'=1:n_factors.africa
#                   )
# null_simulations_matrix.africa.filo<- matrix(0,100,n_factors.africa)
# for (i in 1:100)
# {
#   null_simulations_matrix.africa.filo[i,] <- null_simulations.africa.filo[[i]]$pvals
# }
# null_simulations_matrix.africa.filo <- as.data.frame(t(null_simulations_matrix.africa.filo))
# ddf.africa.filo <- cbind(obs,null_simulations_matrix.africa.filo)
# 
# ddf.africa.filo %>%
#   tidyr::gather(group, pvalue, c(1,3:102)) %>%
#   mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
#   ggplot() +
#   geom_line(aes(x = factor, y= log(pvalue), group = group, color = color))

#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
# The Plot ---------------------------------------------------------------

#............................define our colors....................................................
#.................................................................................................
#............................1:  Yangochiroptera....."#FF0000FF"..................................
#............................2:  Myotis.............."#FF9900FF"..................................
#............................3:  Miniopterus........."#CCFF00FF"..................................
#............................4:  Pteropodidae........"#33FF00FF"..................................
#............................5:  Emballonuroidea....."#00FF66FF"..................................
#............................6:  Rhinolophus........."#00FFFFFF"..................................
#............................7:  Pipistrellini......."#0066FFFF"..................................
#............................8:  Pteropus............"#3300FFFF"..................................
#............................9:  Pteropodidae........"#CC00FFFF".................................
#............................10: Scotophilus kuhlii.."#FF0099FF"..................................
#............................11: Eidolon............."#FF0099FF"..................................
#............................12: Hipposideros........"#00FF66FF"..................................
#............................13: C. perspicillata...."#00FFFFFF"..................................
#............................14: D. rotundus........."#00FFFFFF"..................................
#............................14: Carollia............"#00FFFFFF"..................................
#............................15: Vespertilionoidea..."#00FFFFFF"..................................

colfcn.africa.filo <- function(n) return(c("#CC00FFFF", "#00FFFFFF"))

pf.tree.africa.filo <- pf.tree(pf.africa.filo, factor = 1:2, lwd=1, color.fcn=colfcn.africa.filo, branch.length = "none")
pf.tree.africa.filo$ggplot +
  ggtree::geom_tippoint(size=10*Z,col='blue')  

Legend.africa.filo <- pf.tree.africa.filo$legend
Legend.africa.filo$names <- nms.africa.filo1[1:2]
P.africa.filo <- sapply(probs.africa.phylo,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.africa.filo$names <- mapply(paste,Legend.africa.filo$names,P.africa.filo[1:2])
plot.new()
plot.new()
legend('topleft',legend=Legend.africa.filo$names,fill=Legend.africa.filo$colors,cex=1)


#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#...............POSITIVE AFRICAN BATS................................................
#....................................................................................
#...............POSITIVE AFRICAN BATS................................................
#....................................................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................
#...............POSITIVE AFRICAN BATS................................................


Z.filo.pos <- batphy1.africa$filovirus_positive_cat

n_factors.africa = 10

pf.africa.filo.pos <- phylofactor::twoSampleFactor(Z.filo.pos, africa_tree, method='Fisher', n_factors.africa ,ncores = 1)

taxonomy_africa<- batphy1.africa[,c('species','tax')]

#.................................................................................................
#.................................................................................................
#.................................................................................................
#.............................obtain names........................................................

nms.africa.filo.pos <- list()

for (i in 2:length(pf.africa.filo.pos$bins))
{
  indexes = pf.africa.filo.pos$bins[[i]]
  species_x <- gsub("_", " ", tolower(africa_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy_africa[match(species_x,taxonomy_africa[,1]),2])
  
  nms.africa.filo.pos[i] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))
  
  p<-batphy1 %>%
    filter(tolower(species) %in% species_x) %>%
    group_by(filo_surv) %>%
    summarise(n = n()) 
  
  print(as.numeric(p[2,'n'] / (p[2,'n'] + p[1,'n'])))
  print(i)
}
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#......................END: alex's slack suggestion...............................................

B.africa.phylo.pos <- bins(pf.africa.filo.pos$basis[,1:n_factors.africa])
B.africa.phylo.pos <- B.africa.phylo.pos[2:n_factors.africa] 
nms.africa.filo1.pos <- nms.africa.filo.pos[2:(n_factors.africa+1)]

## remove paraphyletic bin

#probs.africa.phylo.pos <- sapply(B.africa.phylo.pos,FUN=function(ix,Z) mean(Z[ix]),Z=Z) %>% signif(.,digits=2)
#names(nms.africa.filo1.pos) <- probs.africa.phylo.pos

#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#...............Null Simulation..........................................................

# null_simulations.africa.filo.pos <- pf.nullsim(pf.africa.filo.pos, reps = 250, nfactors = n_factors.africa, output ='pvals')
# 
# #nfactors <- pf$nfactors
# obs.filo.africa.pos <- data.frame('Pvals'=pf.africa.filo.pos$pvals,'factor'=1:n_factors.africa)
# 
# null_simulations_matrix.africa.filo.pos<- matrix(0,250,n_factors.africa)
# for (i in 1:250)
# {
#   null_simulations_matrix.africa.filo.pos[i,] <- null_simulations.africa.filo.pos[[i]]$pvals
# }
# null_simulations_matrix.africa.filo.pos <- as.data.frame(t(null_simulations_matrix.africa.filo.pos))
# ddf.africa.filo.pos <- cbind(obs.filo.africa.pos,null_simulations_matrix.africa.filo.pos)
# 
# ddf.africa.filo.pos %>%
#   tidyr::gather(group, pvalue, c(1,3:202)) %>%
#   mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
#   ggplot() +
#   geom_line(aes(x = factor, y= log(pvalue), group = group, color = color)) +
#   scale_x_continuous(limits=c(1, 10), breaks = seq(1,10, by= 1))
# 
# x <- ddf.africa.filo.pos %>%
#   tidyr::gather(group, pvalue, c(1,3:202)) %>%
#   mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) 
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
# The Plot ---------------------------------------------------------------

#............................define our colors....................................................
#.................................................................................................
#............................1:  Yangochiroptera....."#FF0000FF"..................................
#............................2:  Myotis.............."#FF9900FF"..................................
#............................3:  Miniopterus........."#CCFF00FF"..................................
#............................4:  Pteropodidae........"#33FF00FF"..................................
#............................5:  Emballonuroidea....."#00FF66FF"..................................
#............................6:  Rhinolophus........."#00FFFFFF"..................................
#............................7:  Pipistrellini......."#0066FFFF"..................................
#............................8:  Pteropus............"#3300FFFF"..................................
#............................9:  Pteropodidae........"#CC00FFFF".................................
#............................10: Scotophilus kuhlii.."#FF0099FF"..................................
#............................11: Eidolon............."#FF0099FF"..................................
#............................12: Hipposideros........"#00FF66FF"..................................
#............................13: C. perspicillata...."#00FFFFFF"..................................
#............................14: D. rotundus........."#00FFFFFF"..................................
#............................14: Carollia............"#00FFFFFF"..................................
#............................15: Vespertilionoidea..."#00FFFFFF"..................................

colfcn.africa.filo.pos <- function(n) return(c("#CC00FFFF", "#00FFFFFF"))

pf.tree.africa.filo.pos <- pf.tree(pf.africa.filo.pos, factor = 10, lwd=1, branch.length = "none")
pf.tree.africa.filo.pos$ggplot +
  ggtree::geom_tippoint(size=10*Z.filo.pos,col='blue')  

Legend.africa.filo <- pf.tree.africa.filo$legend
Legend.africa.filo$names <- nms.africa.filo1[1:2]
P.africa.filo <- sapply(probs.africa.phylo,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.africa.filo$names <- mapply(paste,Legend.africa.filo$names,P.africa.filo[1:2])
plot.new()
plot.new()
legend('topleft',legend=Legend.africa.filo$names,fill=Legend.africa.filo$colors,cex=1)


















#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#....................................................................................
#.................comparison of henipa and filo......................................

batphy1 <- batphy1 %>%
  mutate(hnv_surv = ifelse(is.na(hnv_surv), 0, hnv_surv)) %>%
  mutate(filo_samps = ifelse(is.na(filo_samps), 0, filo_samps))
  
taxonomy<- batphy1[,c('species','tax')]

n_factors = 10

#........................henipaviruses...............................

n_factors.hnv = 7

Z.hnv <- batphy1$hnv_surv
pf.hnv <- phylofactor::twoSampleFactor(Z.hnv, bat_tree, method='Fisher', n_factors.hnv ,ncores = 1)

nms.hnv <- list()
for (i in 2:(n_factors.hnv+1))
{
  indexes = pf.hnv$bins[[i]]
  species <- gsub("_", " ", tolower(bat_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy[match(species,taxonomy[,1]),2])
  nms.hnv[i-1] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))
  print(i)
}

B.hnv <- bins(pf.hnv$basis[,1:n_factors.hnv])
B.hnv <- B.hnv[2:(n_factors.hnv+1)] 
nms1.hnv <- nms.hnv[1:(n_factors.hnv)]

## remove paraphyletic bin

probs.hnv <- sapply(B.hnv,FUN=function(ix,Z.hnv) mean(Z.hnv[ix]),Z.hnv=Z.hnv) %>% signif(.,digits=2)
names(nms1.hnv) <- probs.hnv

#............................define our colors....................................................
#.................................................................................................
#............................1:  Yangochiroptera....."#FF0000FF"..................................
#............................2:  Myotis.............."#FF9900FF"..................................
#............................3:  Miniopterus........."#CCFF00FF"..................................
#............................4:  Pteropodidae........"#33FF00FF"..................................
#............................5:  Emballonuroidea....."#00FF66FF"..................................
#............................6:  Rhinolophus........."#00FFFFFF"..................................
#............................7:  Pipistrellini......."#0066FFFF"..................................
#............................8:  Pteropus............"#3300FFFF"..................................
#............................9:  Pteropodidae........"#CC00FFFF".................................
#............................10: Scotophilus kuhlii.."#FF0099FF"..................................
#............................11: Eidolon............."#FF0099FF"..................................
#............................12: Hipposideros........"#00FF66FF"..................................
#............................13: C. perspicillata...."#00FFFFFF"..................................
#............................14: D. rotundus........."#00FFFFFF"..................................
#............................14: Carollia............"#00FFFFFF"..................................

colfcn.hnv <- function(n) return(c("#FF0000FF", "#00FFFFFF","#3300FFFF","#33FF00FF","#00FFFFFF","#FF0099FF","#00FF66FF"))

pf.tree.hnv <- pf.tree(pf.hnv, lwd=1, color.fcn=colfcn.hnv, branch.length = "none")
pf.tree.hnv$ggplot +
  ggtree::geom_tippoint(size=10*Z.hnv,col='blue')  

Legend.hnv <- pf.tree.hnv$legend
Legend.hnv$names <- nms1.hnv
P.hnv <- sapply(probs.hnv,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.hnv$names <- mapply(paste,Legend.hnv$names,P.hnv)
plot.new()
plot.new()
legend('topleft',legend=Legend.hnv$names,fill=Legend.hnv$colors,cex=1)

#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#...............Null Simulation..........................................................
# 
# null_simulations.hnv <- readRDS('data/my_phylofactor_object_hvn_nullsim')
# 
# #nfactors <- pf$nfactors
# obs.hnv <- data.frame('Pvals'=pf.hnv$pvals,
#                   'factor'=1:n_factors
# )
# null_simulations_matrix.hnv<- matrix(0,1000,n_factors)
# for (i in 1:1000)
# {
#   null_simulations_matrix.hnv[i,] <- null_simulations.hnv[[i]]$pvals
# }
# null_simulations_matrix.hnv <- as.data.frame(t(null_simulations_matrix.hnv))
# ddf.hnv <- cbind(obs.hnv,null_simulations_matrix.hnv)
# 
# ddf.hnv %>%
#   tidyr::gather(group, pvalue, c(1,3:1002)) %>%
#   mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
#   ggplot() +
#   geom_line(aes(x = factor, y= log(pvalue), group = group, color = color)) +
#   ggtitle('henipavirus virus simulations') + 
#   scale_x_continuous(limits=c(1, 10), breaks = seq(1,10, by= 1))

#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#...................................filo viruses......................................

Z.filo <- batphy1$filo_surv
n_factors.filo = 10
pf.filo <- phylofactor::twoSampleFactor(Z.filo, method='Fisher', bat_tree, n_factors.filo ,ncores = 1)

#nms.filo <- matrix(0,n_factors+1,2)
nms.filo <- list()
for (i in 2:(n_factors.filo+1))
{
  indexes = pf.filo$bins[[i]]
  species_x <- gsub("_", " ", tolower(bat_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy[match(species_x,taxonomy[,1]),2])
  nms.filo[i-1] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))
  
  print(i)
  
  p<-batphy1 %>%
  filter(tolower(species) %in% species_x) %>%
  group_by(filo_surv) %>%
  summarise(n = n()) 
  
  print(as.numeric(p[2,'n'] / (p[2,'n'] + p[1,'n'])))
}

B.filo <- bins(pf.filo$basis[,1:n_factors.filo])
B.filo <- B.filo[2:(n_factors.filo+1)] 
nms1.filo <- nms.filo[1:(n_factors.filo)]

#nms1.hnv <- nms.hnv[2:(n_factors+1)]
## remove paraphyletic bin

probs.filo <- sapply(B.filo,FUN=function(ix,Z.filo) mean(Z.filo[ix]),Z=Z.filo) %>% signif(.,digits=2)
names(nms1.filo) <- probs.filo


#............................define our colors..................................................
#...............................................................................................
#............................1:  Yangochiroptera.....#FF0000FF..................................
#............................2:  Myotis..............#FF9900FF..................................
#............................3:  Miniopterus.........#CCFF00FF..................................
#............................4:  Pteropodidae........#33FF00FF..................................
#............................5:  Emballonuroidea.....#FF004DFF..................................
#............................6:  Rhinolophus.........#00FFFFFF..................................
#............................7:  Pipistrellini.......#0066FFFF..................................
#............................8:  Pteropus............#3300FFFF..................................
#............................9:  Pteropodidae........#CC00FFFF".................................
#............................10: Scotophilus kuhlii..#FF0099FF..................................

colfcn.filo <- function(n) return(c("#FF0000FF", "#FF9900FF" ,"#CCFF00FF" ,"#33FF00FF", "#FF00E6FF", "#00FFFFFF" ,"#0066FFFF", "#3300FFFF")) #,"#CC00FFFF" ,"#FF0099FF"))
  
pf.tree.filo <- pf.tree(pf.filo, lwd=1, color.fcn = colfcn.filo, factors = 1:8, branch.length = "none")

pf.tree.filo$ggplot +
  ggtree::geom_tippoint(size=10*Z.filo,col='blue')  

Legend.filo <- pf.tree.filo$legend
Legend.filo$names <- nms1.filo[1:8]
P.filo <- sapply(probs.filo,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.filo$names <- mapply(paste,Legend.filo$names,P.filo[1:8])
plot.new()
plot.new()
legend('topleft',legend=Legend.filo$names,fill=Legend.filo$colors,cex=1)


#legend('topleft',legend=Legend[1,'names'],fill=Legend[1,'colors'],cex=1.8)

#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#........................................................................................
#...............Null Simulation..........................................................

#null_simulations <- pf.nullsim(pf.filo, reps = 50, nfactors = n_factors, output ='pvals')
null_simulations.filo <- readRDS('data/my_phylofactor_object_filo_nullsim')

#nfactors <- pf$nfactors
obs <- data.frame('Pvals'=pf.filo$pvals,
                  'factor'=1:n_factors.filo
                  )
null_simulations_matrix<- matrix(0,1000,n_factors.filo)
for (i in 1:1000)
{
  null_simulations_matrix[i,] <- null_simulations.filo[[i]]$pvals
}
null_simulations_matrix <- as.data.frame(t(null_simulations_matrix))
ddf.filo <- cbind(obs,null_simulations_matrix)

ddf.filo %>%
  tidyr::gather(group, pvalue, c(1,3:1002)) %>%
  mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
  ggplot() +
  geom_line(aes(x = factor, y= log(pvalue), group = group, color = color)) +
  ggtitle('filo virus simulations') +
  scale_x_continuous(limits=c(1, 10), breaks = seq(1,10, by= 1))
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................

#Yinpterochiroptera is the group that is not Yangochiroptera 


#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.................................................................................................
#.............add in filovirus and henipavirus positivity....................

#setwd("/Users/buckcrowley/Desktop/BDEL/BZDEL/meta_analysis/")

#.............henipavirus positivity....................

n_factors.hnv.pos = 10

Z.hnv_pos <- batphy1$henipavirus_positive_cat
pf.hnv_pos <- phylofactor::twoSampleFactor(Z.hnv_pos, bat_tree, method='Fisher', n_factors.hnv.pos ,ncores = 1)

nms.hnv.pos <- list()
for (i in 2:(n_factors.hnv.pos+1))
{
  indexes = pf.hnv_pos$bins[[i]]
  species_x <- gsub("_", " ", tolower(bat_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy[match(species_x,taxonomy[,1]),2])
  nms.hnv.pos[i-1] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))
  #print(i)
  print(gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list))))
  #p<-batphy1 %>%
  #  filter(tolower(species) %in% species_x) %>%
  #  group_by(henipavirus_positive_cat) %>%
  #  summarise(n = n()) 
  #print(p)
}

B.hnv.pos <- bins(pf.hnv_pos$basis[,1:n_factors.hnv.pos])
B.hnv.pos <- B.hnv.pos[2:(n_factors.hnv.pos+1)] 
nms1.hnv.pos <- nms.hnv.pos[1:(n_factors.hnv.pos)]

## remove paraphyletic bin

probs.hnv.pos <- sapply(B.hnv.pos,FUN=function(ix,Z.hnv_pos) mean(Z.hnv_pos[ix]),Z.hnv_pos=Z.hnv_pos) %>% signif(.,digits=2)
names(nms1.hnv.pos) <- probs.hnv.pos

null_simulations.hnv.pos <- pf.nullsim(pf.hnv_pos, reps = 100, nfactors = n_factors.hnv.pos, output ='pvals')

obs <- data.frame('Pvals'=pf.hnv_pos$pvals,
                  'factor'=1:n_factors.hnv.pos
)
null_simulations_matrix.hnv.pos<- matrix(0,100,n_factors.hnv.pos)
for (i in 1:100)
{
  null_simulations_matrix.hnv.pos[i,] <- null_simulations.hnv.pos[[i]]$pvals
}
null_simulations_matrix.hnv.pos <- as.data.frame(t(null_simulations_matrix.hnv.pos))
ddf.hnv.pos <- cbind(obs,null_simulations_matrix.hnv.pos)

ddf.hnv.pos %>%
  tidyr::gather(group, pvalue, c(1,3:102)) %>%
  mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
  ggplot() +
  geom_line(aes(x = factor, y= log(pvalue), group = group, color = color)) +
  ggtitle('filo virus simulations') +
  scale_x_continuous(limits=c(1, 10), breaks = seq(1,10, by= 1))


#............................define our colors....................................................
#.................................................................................................
#............................1:  Yangochiroptera....."#FF0000FF"..................................
#............................2:  Myotis.............."#FF9900FF"..................................
#............................3:  Miniopterus........."#CCFF00FF"..................................
#............................4:  Pteropodidae........"#33FF00FF"..................................
#............................5:  Emballonuroidea....."#00FF66FF"..................................
#............................6:  Rhinolophus........."#00FFFFFF"..................................
#............................7:  Pipistrellini......."#0066FFFF"..................................
#............................8:  Pteropus............"#3300FFFF"..................................
#............................9:  Pteropodidae........"#CC00FFFF".................................
#............................10: Scotophilus kuhlii.."#FF0099FF"..................................
#............................11: Eidolon............."#FF0099FF"..................................
#............................12: Hipposideros........"#00FF66FF"..................................


colfcn.hnv.pos <- function(n) return(c("#33FF00FF"))

pf.tree.hnv.pos <- pf.tree(pf.hnv_pos, lwd=1, factors =1, color.fcn = colfcn.hnv.pos, branch.length = "none")
pf.tree.hnv.pos$ggplot +
  ggtree::geom_tippoint(size=10*Z.hnv_pos,col='blue')  

Legend.hnv.pos <- pf.tree.hnv.pos$legend
Legend.hnv.pos$names <- nms1.hnv.pos[1]
P.hnv.pos <- sapply(probs.hnv.pos,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.hnv.pos$names <- mapply(paste,Legend.hnv.pos$names,P.hnv.pos[1])
plot.new()
plot.new()
legend('topleft',legend=Legend.hnv.pos$names,fill=Legend.hnv.pos$colors,cex=1)

#.............add in filovirus positivity....................

n_factors.filo.pos = 10

Z.filo_pos <- batphy1$filovirus_positive_cat
pf.filo_pos <- phylofactor::twoSampleFactor(Z.filo_pos, bat_tree, method='Fisher', n_factors.filo.pos ,ncores = 1)

nms.filo.pos <- list()
for (i in 2:(n_factors.filo.pos+1))
{
  indexes = pf.filo_pos$bins[[i]]
  species_x <- gsub("_", " ", tolower(bat_tree$tip.label[indexes]))
  group_taxonomy_list <- as.data.frame(taxonomy[match(species_x,taxonomy[,1]),2])
  nms.filo.pos[i-1] <- gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list)))
  print(i)
  
  print(gsub("\\)|;","", as.character(taxonomy_group_name(group_taxonomy_list))))
  p<-batphy1 %>%
    filter(tolower(species) %in% species_x) %>%
    group_by(filovirus_positive_cat) %>%
    summarise(n = n()) 
  print(p)
}

B.filo.pos <- bins(pf.filo_pos$basis[,1:n_factors.filo.pos])
B.filo.pos <- B.filo.pos[2:(n_factors.filo.pos+1)] 
nms1.filo.pos <- nms.filo.pos[1:(n_factors.filo.pos)]

## remove paraphyletic bin

probs.filo.pos <- sapply(B.filo.pos,FUN=function(ix,Z.filo_pos) mean(Z.filo_pos[ix]),Z.filo_pos=Z.filo_pos) %>% signif(.,digits=2)
names(nms1.filo.pos) <- probs.filo.pos

null_simulations.filo.pos <- pf.nullsim(pf.filo_pos, reps = 100, nfactors = n_factors.filo.pos, output ='pvals')

obs.filo.pos <- data.frame('Pvals'=pf.filo_pos$pvals,
                  'factor'=1:n_factors.filo.pos
)


null_simulations_matrix.filo.pos<- matrix(0,100,n_factors.filo.pos)
for (i in 1:100)
{
  null_simulations_matrix.filo.pos[i,] <- null_simulations.filo.pos[[i]]$pvals
}
null_simulations_matrix.filo.pos <- as.data.frame(t(null_simulations_matrix.filo.pos))
ddf.filo.pos <- cbind(obs.filo.pos,null_simulations_matrix.filo.pos)

ddf.filo.pos %>%
  tidyr::gather(group, pvalue, c(1,3:102)) %>%
  mutate(color = ifelse(group =='Pvals', "observed", 'simulated')) %>%
  ggplot() +
  geom_line(aes(x = factor, y= log(pvalue), group = group, color = color)) +
  ggtitle('filo virus simulations') +
  scale_x_continuous(limits=c(1, 10), breaks = seq(1,10, by= 1))



#............................define our colors....................................................
#.................................................................................................
#............................1:  Yangochiroptera....."#FF0000FF"..................................
#............................2:  Myotis.............."#FF9900FF"..................................
#............................3:  Miniopterus........."#CCFF00FF"..................................
#............................4:  Pteropodidae........"#33FF00FF"..................................
#............................5:  Emballonuroidea....."#00FF66FF"..................................
#............................6:  Rhinolophus........."#00FFFFFF"..................................
#............................7:  Pipistrellini......."#0066FFFF"..................................
#............................8:  Pteropus............"#3300FFFF"..................................
#............................9:  Pteropodidae........"#CC00FFFF".................................
#............................10: Scotophilus kuhlii.."#FF0099FF"..................................
#............................11: Eidolon............."#FF0099FF"..................................
#............................12: Hipposideros........"#00FF66FF"..................................
#............................13: C. perspicillata...."#00FFFFFF"..................................
#............................14: D. rotundus........."#0066FFFF"..................................

colfcn.filo.pos <- function(n) return(c("#33FF00FF"))

pf.tree.filo.pos <- pf.tree(pf.filo_pos, lwd=1, factors =1, color.fcn = colfcn.filo.pos, branch.length = "none")
pf.tree.filo.pos$ggplot +
  ggtree::geom_tippoint(size=10*Z.filo_pos,col='blue')  

Legend.filo.pos <- pf.tree.filo.pos$legend
Legend.filo.pos$names <- nms1.filo.pos[1]
P.filo.pos <- sapply(probs.filo.pos,FUN=function(x) paste('p=',toString(signif(x,digits = 2)),sep=''))
Legend.filo.pos$names <- mapply(paste,Legend.filo.pos$names,P.filo.pos[1])
plot.new()
plot.new()
legend('topleft',legend=Legend.filo.pos$names,fill=Legend.filo.pos$colors,cex=1)
