# source of names: http://www.africanbats.org/Documents/ACR/2014/
# source of names: https://www.africanbats.org/Documents/ACR/2014/ACR_2014_main.pdf

X<- ('asellia_tridens.dbf
asellia_tridens.shp
     asellia_tridens.shx
     barbastella_barbastellus.dbf
     barbastella_barbastellus.shp
     barbastella_barbastellus.shx
     cardioderma_cor.dbf
     cardioderma_cor.shp
     cardioderma_cor.shx
     cardioderma.dbf
     cardioderma.shp
     cardioderma.shx
     casinycteris_argynnis.dbf
     casinycteris_argynnis.shp
     casinycteris_argynnis.shx
     chaerephon_aloysiisabaudiae.dbf
     chaerephon_aloysiisabaudiae.shp
     chaerephon_aloysiisabaudiae.shx
     chaerephon_ansorgei.dbf
     chaerephon_ansorgei.shp
     chaerephon_ansorgei.shx
     chaerephon_atsinanana.dbf
     chaerephon_atsinanana.shp
     chaerephon_atsinanana.shx
     chaerephon_bemmeleni.dbf
     chaerephon_bemmeleni.shp
     chaerephon_bemmeleni.shx
     chaerephon_bivittatus.dbf
     chaerephon_bivittatus.shp
     chaerephon_bivittatus.shx
     chaerephon_chapini.dbf
     chaerephon_chapini.shp
     chaerephon_chapini.shx
     chaerephon_gallagheri.dbf
     chaerephon_gallagheri.shp
     chaerephon_gallagheri.shx
     chaerephon_jobimena.dbf
     chaerephon_jobimena.shp
     chaerephon_jobimena.shx
     chaerephon_leucogaster.dbf
     chaerephon_leucogaster.shp
     chaerephon_leucogaster.shx
     chaerephon_major.dbf
     chaerephon_major.shp
     chaerephon_major.shx
     chaerephon_nigeriae_nigeriae.dbf
     chaerephon_nigeriae_nigeriae.shp
     chaerephon_nigeriae_nigeriae.shx
     chaerephon_nigeriae_spillmanni.dbf
     chaerephon_nigeriae_spillmanni.shp
     chaerephon_nigeriae_spillmanni.shx
     chaerephon_nigeriae.dbf
     chaerephon_nigeriae.shp
     chaerephon_nigeriae.shx
     chaerephon_pumilus.dbf
     chaerephon_pumilus.shp
     chaerephon_pumilus.shx
     chaerephon_pusillus.dbf
     chaerephon_pusillus.shp
     chaerephon_pusillus.shx
     chaerephon_russatus.dbf
     chaerephon_russatus.shp
     chaerephon_russatus.shx
     chaerephon_tomensis.dbf
     chaerephon_tomensis.shp
     chaerephon_tomensis.shx
     chaerephon.dbf
     chaerephon.shp
     chaerephon.shx
     chiroptera.dbf
     chiroptera.shp
     chiroptera.shx
     cistugo_lesueuri.dbf
     cistugo_lesueuri.shp
     cistugo_lesueuri.shx
     cistugo_seabrae.dbf
     cistugo_seabrae.shp
     cistugo_seabrae.shx
     cloeotis_percivali.dbf
     cloeotis_percivali.shp
     cloeotis_percivali.shx
     cloeotis.dbf
     cloeotis.shp
     cloeotis.shx
     coleura_afra.dbf
     coleura_afra.shp
     coleura_afra.shx
     coleura_seychellensis.dbf
     coleura_seychellensis.shp
     coleura_seychellensis.shx
     eidolon_dupreanum.dbf
     eidolon_dupreanum.shp
     eidolon_dupreanum.shx
     eidolon_helvum_helvum.dbf
     eidolon_helvum_helvum.shp
     eidolon_helvum_helvum.shx
     eidolon_helvum.dbf
     eidolon_helvum.shp
     eidolon_helvum.shx
     emballonura_atrata.dbf
     emballonura_atrata.shp
     emballonura_atrata.shx
     emballonura_tiavato.dbf
     emballonura_tiavato.shp
     emballonura_tiavato.shx
     emballonuridae.dbf
     emballonuridae.shp
     emballonuridae.shx
     epomophorus_angolensis.dbf
     epomophorus_angolensis.shp
     epomophorus_angolensis.shx
     epomophorus_anselli.dbf
     epomophorus_anselli.shp
     epomophorus_anselli.shx
     epomophorus_crypturus.dbf
     epomophorus_crypturus.shp
     epomophorus_crypturus.shx
     epomophorus_gambianus_gambianus.dbf
     epomophorus_gambianus_gambianus.shp
     epomophorus_gambianus_gambianus.shx
     epomophorus_gambianus_pousarguesi.dbf
     epomophorus_gambianus_pousarguesi.shp
     epomophorus_gambianus_pousarguesi.shx
     epomophorus_gambianus.dbf
     epomophorus_gambianus.shp
     epomophorus_gambianus.shx
     epomophorus_grandis.dbf
     epomophorus_grandis.shp
     epomophorus_grandis.shx
     epomophorus_labiatus.dbf
     epomophorus_labiatus.shp
     epomophorus_labiatus.shx
     epomophorus_minimus.dbf
     epomophorus_minimus.shp
     epomophorus_minimus.shx
     epomophorus_minor.dbf
     epomophorus_minor.shp
     epomophorus_minor.shx
     epomophorus_wahlbergi.dbf
     epomophorus_wahlbergi.shp
     epomophorus_wahlbergi.shx
     epomophorus.dbf
     epomophorus.shp
     epomophorus.shx
     epomops_buettikoferi.dbf
     epomops_buettikoferi.shp
     epomops_buettikoferi.shx
     epomops_dobsonii.dbf
     epomops_dobsonii.shp
     epomops_dobsonii.shx
     epomops_franqueti.dbf
     epomops_franqueti.shp
     epomops_franqueti.shx
     epomops.dbf
     epomops.shp
     epomops.shx
     eptesicus_bottae.dbf
     eptesicus_bottae.shp
     eptesicus_bottae.shx
     eptesicus_floweri.dbf
     eptesicus_floweri.shp
     eptesicus_floweri.shx
     eptesicus_hottentotus.dbf
     eptesicus_hottentotus.shp
     eptesicus_hottentotus.shx
     eptesicus_isabellinus.dbf
     eptesicus_isabellinus.shp
     eptesicus_isabellinus.shx
     eptesicus_platyops.dbf
     eptesicus_platyops.shp
     eptesicus_platyops.shx
     eptesicus.dbf
     eptesicus.shp
     eptesicus.shx
     glauconycteris_alboguttata.dbf
     glauconycteris_alboguttata.shp
     glauconycteris_alboguttata.shx
     glauconycteris_argentata.dbf
     glauconycteris_argentata.shp
     glauconycteris_argentata.shx
     glauconycteris_beatrix.dbf
     glauconycteris_beatrix.shp
     glauconycteris_beatrix.shx
     glauconycteris_curryae.dbf
     glauconycteris_curryae.shp
     glauconycteris_curryae.shx
     glauconycteris_egeria.dbf
     glauconycteris_egeria.shp
     glauconycteris_egeria.shx
     glauconycteris_gleni.dbf
     glauconycteris_gleni.shp
     glauconycteris_gleni.shx
     glauconycteris_humeralis.dbf
     glauconycteris_humeralis.shp
     glauconycteris_humeralis.shx
     glauconycteris_kenyacola.dbf
     glauconycteris_kenyacola.shp
     glauconycteris_kenyacola.shx
     glauconycteris_machadoi.dbf
     glauconycteris_machadoi.shp
     glauconycteris_machadoi.shx
     glauconycteris_poensis.dbf
     glauconycteris_poensis.shp
     glauconycteris_poensis.shx
     glauconycteris_superba.dbf
     glauconycteris_superba.shp
     glauconycteris_superba.shx
     glauconycteris_variegata.dbf
     glauconycteris_variegata.shp
     glauconycteris_variegata.shx
     glauconycteris.dbf
     glauconycteris.shp
     glauconycteris.shx
     hipposideridae.dbf
     hipposideridae.shp
     hipposideridae.shx
     hipposideros_abae.dbf
     hipposideros_abae.shp
     hipposideros_abae.shx
     hipposideros_beatus.dbf
     hipposideros_beatus.shp
     hipposideros_beatus.shx
     hipposideros_besaoka.dbf
     hipposideros_besaoka.shp
     hipposideros_besaoka.shx
     hipposideros_caffer.dbf
     hipposideros_caffer.shp
     hipposideros_caffer.shx
     hipposideros_camerunensis.dbf
     hipposideros_camerunensis.shp
     hipposideros_camerunensis.shx
     hipposideros_commersoni.dbf
     hipposideros_commersoni.shp
     hipposideros_commersoni.shx
     hipposideros_curtus.dbf
     hipposideros_curtus.shp
     hipposideros_curtus.shx
     hipposideros_cyclops.dbf
     hipposideros_cyclops.shp
     hipposideros_cyclops.shx
     hipposideros_fuliginosus.dbf
     hipposideros_fuliginosus.shp
     hipposideros_fuliginosus.shx
     hipposideros_gigas.dbf
     hipposideros_gigas.shp
     hipposideros_gigas.shx
     hipposideros_jonesi.dbf
     hipposideros_jonesi.shp
     hipposideros_jonesi.shx
     hipposideros_lamottei.dbf
     hipposideros_lamottei.shp
     hipposideros_lamottei.shx
     hipposideros_marisae.dbf
     hipposideros_marisae.shp
     hipposideros_marisae.shx
     hipposideros_megalotis.dbf
     hipposideros_megalotis.shp
     hipposideros_megalotis.shx
     hipposideros_ruber.dbf
     hipposideros_ruber.shp
     hipposideros_ruber.shx
     hipposideros_tephrus.dbf
     hipposideros_tephrus.shp
     hipposideros_tephrus.shx
     hipposideros_vittatus.dbf
     hipposideros_vittatus.shp
     hipposideros_vittatus.shx
     hipposideros.dbf
     hipposideros.shp
     hipposideros.shx
     hypsignathus_monstrosus.dbf
     hypsignathus_monstrosus.shp
     hypsignathus_monstrosus.shx
     hypsugo_anchietae.dbf
     hypsugo_anchietae.shp
     hypsugo_anchietae.shx
     hypsugo_ariel.dbf
     hypsugo_ariel.shp
     hypsugo_ariel.shx
     hypsugo_crassulus.dbf
     hypsugo_crassulus.shp
     hypsugo_crassulus.shx
     hypsugo_eisentrauti.dbf
     hypsugo_eisentrauti.shp
     hypsugo_eisentrauti.shx
     hypsugo_musciculus.dbf
     hypsugo_musciculus.shp
     hypsugo_musciculus.shx
     hypsugo_savii.dbf
     hypsugo_savii.shp
     hypsugo_savii.shx
     kerivoula_africana.dbf
     kerivoula_africana.shp
     kerivoula_africana.shx
     kerivoula_argentata.dbf
     kerivoula_argentata.shp
     kerivoula_argentata.shx
     kerivoula_cuprosa.dbf
     kerivoula_cuprosa.shp
     kerivoula_cuprosa.shx
     kerivoula_lanosa.dbf
     kerivoula_lanosa.shp
     kerivoula_lanosa.shx
     kerivoula_phalaena.dbf
     kerivoula_phalaena.shp
     kerivoula_phalaena.shx
     kerivoula_smithii.dbf
     kerivoula_smithii.shp
     kerivoula_smithii.shx
     kerivoula.dbf
     kerivoula.shp
     kerivoula.shx
     laephotis_angolensis.dbf
     laephotis_angolensis.shp
     laephotis_angolensis.shx
     laephotis_botswanae.dbf
     laephotis_botswanae.shp
     laephotis_botswanae.shx
     laephotis_namibensis.dbf
     laephotis_namibensis.shp
     laephotis_namibensis.shx
     laephotis_wintoni.dbf
     laephotis_wintoni.shp
     laephotis_wintoni.shx
     lavia_frons.dbf
     lavia_frons.shp
     lavia_frons.shx
     lissonycteris_angolensis_angolensis.dbf
     lissonycteris_angolensis_angolensis.shp
     lissonycteris_angolensis_angolensis.shx
     lissonycteris_angolensis_ruwenzorii.dbf
     lissonycteris_angolensis_ruwenzorii.shp
     lissonycteris_angolensis_ruwenzorii.shx
     lissonycteris_angolensis.dbf
     lissonycteris_angolensis.shp
     lissonycteris_angolensis.shx
     lissonycteris_goliath.dbf
     lissonycteris_goliath.shp
     lissonycteris_goliath.shx
     lissonycteris_petraea.dbf
     lissonycteris_petraea.shp
     lissonycteris_petraea.shx
     lissonycteris_smithii.dbf
     lissonycteris_smithii.shp
     lissonycteris_smithii.shx
     megaloglossus_woermanni.dbf
     megaloglossus_woermanni.shp
     megaloglossus_woermanni.shx
     micropteropus_intermedius.dbf
     micropteropus_intermedius.shp
     micropteropus_intermedius.shx
     micropteropus_pusillus.dbf
     micropteropus_pusillus.shp
     micropteropus_pusillus.shx
     micropteropus.dbf
     micropteropus.shp
     micropteropus.shx
     mimetillus_moloneyi.dbf
     mimetillus_moloneyi.shp
     mimetillus_moloneyi.shx
     mimetillus_thomasi.dbf
     mimetillus_thomasi.shp
     mimetillus_thomasi.shx
     mimetillus.dbf
     mimetillus.shp
     mimetillus.shx
     miniopterus_aelleni.dbf
     miniopterus_aelleni.shp
     miniopterus_aelleni.shx
     miniopterus_africanus.dbf
     miniopterus_africanus.shp
     miniopterus_africanus.shx
     miniopterus_brachytragos.dbf
     miniopterus_brachytragos.shp
     miniopterus_brachytragos.shx
     miniopterus_egeri.dbf
     miniopterus_egeri.shp
     miniopterus_egeri.shx
     miniopterus_fraterculus.dbf
     miniopterus_fraterculus.shp
     miniopterus_fraterculus.shx
     miniopterus_gleni.dbf
     miniopterus_gleni.shp
     miniopterus_gleni.shx
     miniopterus_griffithsii.dbf
     miniopterus_griffithsii.shp
     miniopterus_griffithsii.shx
     miniopterus_griveaudi.dbf
     miniopterus_griveaudi.shp
     miniopterus_griveaudi.shx
     miniopterus_inflatus_inflatus.dbf
     miniopterus_inflatus_inflatus.shp
     miniopterus_inflatus_inflatus.shx
     miniopterus_inflatus_rufus.dbf
     miniopterus_inflatus_rufus.shp
     miniopterus_inflatus_rufus.shx
     miniopterus_inflatus.dbf
     miniopterus_inflatus.shp
     miniopterus_inflatus.shx
     miniopterus_mahafaliensis.dbf
     miniopterus_mahafaliensis.shp
     miniopterus_mahafaliensis.shx
     miniopterus_majori.dbf
     miniopterus_majori.shp
     miniopterus_majori.shx
     miniopterus_manavi.dbf
     miniopterus_manavi.shp
     miniopterus_manavi.shx
     miniopterus_minor.dbf
     miniopterus_minor.shp
     miniopterus_minor.shx
     miniopterus_natalensis.dbf
     miniopterus_natalensis.shp
     miniopterus_natalensis.shx
     miniopterus_newtoni.dbf
     miniopterus_newtoni.shp
     miniopterus_newtoni.shx
     miniopterus_petersoni.dbf
     miniopterus_petersoni.shp
     miniopterus_petersoni.shx
     miniopterus_schreibersii.dbf
     miniopterus_schreibersii.shp
     miniopterus_schreibersii.shx
     miniopterus_sororculus.dbf
     miniopterus_sororculus.shp
     miniopterus_sororculus.shx
     miniopterus.dbf
     miniopterus.shp
     miniopterus.shx
     molossidae.dbf
     molossidae.shp
     molossidae.shx
     mops__mops__condylurus.dbf
     mops__mops__condylurus.shp
     mops__mops__condylurus.shx
     mops__mops__congicus.dbf
     mops__mops__congicus.shp
     mops__mops__congicus.shx
     mops__mops__demonstrator.dbf
     mops__mops__demonstrator.shp
     mops__mops__demonstrator.shx
     mops__mops__leucostigma.dbf
     mops__mops__leucostigma.shp
     mops__mops__leucostigma.shx
     mops__mops__midas_miarensis.dbf
     mops__mops__midas_miarensis.shp
     mops__mops__midas_miarensis.shx
     mops__mops__midas_midas.dbf
     mops__mops__midas_midas.shp
     mops__mops__midas_midas.shx
     mops__mops__midas.dbf
     mops__mops__midas.shp
     mops__mops__midas.shx
     mops__mops__niangarae.dbf
     mops__mops__niangarae.shp
     mops__mops__niangarae.shx
     mops__mops__niveiventer.dbf
     mops__mops__niveiventer.shp
     mops__mops__niveiventer.shx
     mops__mops__trevori.dbf
     mops__mops__trevori.shp
     mops__mops__trevori.shx
     mops__xiphonycteris__bakarii.dbf
     mops__xiphonycteris__bakarii.shp
     mops__xiphonycteris__bakarii.shx
     mops__xiphonycteris__brachypterus.dbf
     mops__xiphonycteris__brachypterus.shp
     mops__xiphonycteris__brachypterus.shx
     mops__xiphonycteris__nanulus.dbf
     mops__xiphonycteris__nanulus.shp
     mops__xiphonycteris__nanulus.shx
     mops__xiphonycteris__petersoni.dbf
     mops__xiphonycteris__petersoni.shp
     mops__xiphonycteris__petersoni.shx
     mops__xiphonycteris__spurrelli.dbf
     mops__xiphonycteris__spurrelli.shp
     mops__xiphonycteris__spurrelli.shx
     mops__xiphonycteris__thersites.dbf
     mops__xiphonycteris__thersites.shp
     mops__xiphonycteris__thersites.shx
     mops_rusingae.dbf
     mops_rusingae.shp
     mops_rusingae.shx
     mops.dbf
     mops.shp
     mops.shx
     mormopterus_acetabulosus.dbf
     mormopterus_acetabulosus.shp
     mormopterus_acetabulosus.shx
     mormopterus_francoismoutoui.dbf
     mormopterus_francoismoutoui.shp
     mormopterus_francoismoutoui.shx
     mormopterus_jugularis.dbf
     mormopterus_jugularis.shp
     mormopterus_jugularis.shx
     mormopterus.dbf
     mormopterus.shp
     mormopterus.shx
     myonycteris__myonycteris__leptodon.dbf
     myonycteris__myonycteris__leptodon.shp
     myonycteris__myonycteris__leptodon.shx
     myonycteris__myonycteris__relicta.dbf
     myonycteris__myonycteris__relicta.shp
     myonycteris__myonycteris__relicta.shx
     myonycteris__myonycteris__torquata_torquata.dbf
     myonycteris__myonycteris__torquata_torquata.shp
     myonycteris__myonycteris__torquata_torquata.shx
     myonycteris__myonycteris__torquata_wroughtoni.dbf
     myonycteris__myonycteris__torquata_wroughtoni.shp
     myonycteris__myonycteris__torquata_wroughtoni.shx
     myonycteris__myonycteris__torquata.dbf
     myonycteris__myonycteris__torquata.shp
     myonycteris__myonycteris__torquata.shx
     myonycteris__phygetis__brachycephala.dbf
     myonycteris__phygetis__brachycephala.shp
     myonycteris__phygetis__brachycephala.shx
     myopterus_daubentonii.dbf
     myopterus_daubentonii.shp
     myopterus_daubentonii.shx
     myopterus_whitleyi.dbf
     myopterus_whitleyi.shp
     myopterus_whitleyi.shx
     myotis_anjouanensis.dbf
     myotis_anjouanensis.shp
     myotis_anjouanensis.shx
     myotis_bocagii_bocagii.dbf
     myotis_bocagii_bocagii.shp
     myotis_bocagii_bocagii.shx
     myotis_bocagii_cupreolus.dbf
     myotis_bocagii_cupreolus.shp
     myotis_bocagii_cupreolus.shx
     myotis_bocagii.dbf
     myotis_bocagii.shp
     myotis_bocagii.shx
     myotis_capaccinii.dbf
     myotis_capaccinii.shp
     myotis_capaccinii.shx
     myotis_dieteri.dbf
     myotis_dieteri.shp
     myotis_dieteri.shx
     myotis_emarginatus.dbf
     myotis_emarginatus.shp
     myotis_emarginatus.shx
     myotis_goudoti.dbf
     myotis_goudoti.shp
     myotis_goudoti.shx
     myotis_morrisi.dbf
     myotis_morrisi.shp
     myotis_morrisi.shx
     myotis_punicus.dbf
     myotis_punicus.shp
     myotis_punicus.shx
     myotis_scotti.dbf
     myotis_scotti.shp
     myotis_scotti.shx
     myotis_tricolor.dbf
     myotis_tricolor.shp
     myotis_tricolor.shx
     myotis_welwitschii.dbf
     myotis_welwitschii.shp
     myotis_welwitschii.shx
     myotis.dbf
     myotis.shp
     myotis.shx
     myzopoda_aurita.dbf
     myzopoda_aurita.shp
     myzopoda_aurita.shx
     myzopoda_schliemanni.dbf
     myzopoda_schliemanni.shp
     myzopoda_schliemanni.shx
     nanonycteris_veldkampii.dbf
     nanonycteris_veldkampii.shp
     nanonycteris_veldkampii.shx
     neoromicia__incertae_sedis_.dbf
     neoromicia__incertae_sedis_.shp
     neoromicia__incertae_sedis_.shx
     neoromicia_brunnea.dbf
     neoromicia_brunnea.shp
     neoromicia_brunnea.shx
     neoromicia_capensis.dbf
     neoromicia_capensis.shp
     neoromicia_capensis.shx
     neoromicia_flavescens.dbf
     neoromicia_flavescens.shp
     neoromicia_flavescens.shx
     neoromicia_guineensis.dbf
     neoromicia_guineensis.shp
     neoromicia_guineensis.shx
     neoromicia_helios.dbf
     neoromicia_helios.shp
     neoromicia_helios.shx
     neoromicia_humbloti.dbf
     neoromicia_humbloti.shp
     neoromicia_humbloti.shx
     neoromicia_malagasyensis.dbf
     neoromicia_malagasyensis.shp
     neoromicia_malagasyensis.shx
     neoromicia_matroka.dbf
     neoromicia_matroka.shp
     neoromicia_matroka.shx
     neoromicia_melckorum.dbf
     neoromicia_melckorum.shp
     neoromicia_melckorum.shx
     neoromicia_nana.dbf
     neoromicia_nana.shp
     neoromicia_nana.shx
     neoromicia_rendalli.dbf
     neoromicia_rendalli.shp
     neoromicia_rendalli.shx
     neoromicia_robertsi.dbf
     neoromicia_robertsi.shp
     neoromicia_robertsi.shx
     neoromicia_roseveari.dbf
     neoromicia_roseveari.shp
     neoromicia_roseveari.shx
     neoromicia_somalica.dbf
     neoromicia_somalica.shp
     neoromicia_somalica.shx
     neoromicia_sp_aff_melckorum.dbf
     neoromicia_sp_aff_melckorum.shp
     neoromicia_sp_aff_melckorum.shx
     neoromicia_tenuipinnis.dbf
     neoromicia_tenuipinnis.shp
     neoromicia_tenuipinnis.shx
     neoromicia_zuluensis.dbf
     neoromicia_zuluensis.shp
     neoromicia_zuluensis.shx
     neoromicia.dbf
     neoromicia.shp
     neoromicia.shx
     nyctalus_azoreum.dbf
     nyctalus_azoreum.shp
     nyctalus_azoreum.shx
     nyctalus_leisleri.dbf
     nyctalus_leisleri.shp
     nyctalus_leisleri.shx
     nycteridae.dbf
     nycteridae.shp
     nycteridae.shx
     nycteris_arge.dbf
     nycteris_arge.shp
     nycteris_arge.shx
     nycteris_aurita.dbf
     nycteris_aurita.shp
     nycteris_aurita.shx
     nycteris_gambiensis.dbf
     nycteris_gambiensis.shp
     nycteris_gambiensis.shx
     nycteris_grandis.dbf
     nycteris_grandis.shp
     nycteris_grandis.shx
     nycteris_hispida.dbf
     nycteris_hispida.shp
     nycteris_hispida.shx
     nycteris_intermedia.dbf
     nycteris_intermedia.shp
     nycteris_intermedia.shx
     nycteris_macrotis.dbf
     nycteris_macrotis.shp
     nycteris_macrotis.shx
     nycteris_madagascariensis.dbf
     nycteris_madagascariensis.shp
     nycteris_madagascariensis.shx
     nycteris_major.dbf
     nycteris_major.shp
     nycteris_major.shx
     nycteris_nana.dbf
     nycteris_nana.shp
     nycteris_nana.shx
     nycteris_parisii.dbf
     nycteris_parisii.shp
     nycteris_parisii.shx
     nycteris_thebaica.dbf
     nycteris_thebaica.shp
     nycteris_thebaica.shx
     nycteris_vinsoni.dbf
     nycteris_vinsoni.shp
     nycteris_vinsoni.shx
     nycteris_woodi.dbf
     nycteris_woodi.shp
     nycteris_woodi.shx
     nycteris.dbf
     nycteris.shp
     nycteris.shx
     nycticeinops_schlieffenii.dbf
     nycticeinops_schlieffenii.shp
     nycticeinops_schlieffenii.shx
     nycticeinops.dbf
     nycticeinops.shp
     nycticeinops.shx
     otomops_madagascariensis.dbf
     otomops_madagascariensis.shp
     otomops_madagascariensis.shx
     otomops_martiensseni_icarus.dbf
     otomops_martiensseni_icarus.shp
     otomops_martiensseni_icarus.shx
     otomops_martiensseni_martiensseni.dbf
     otomops_martiensseni_martiensseni.shp
     otomops_martiensseni_martiensseni.shx
     otomops_martiensseni.dbf
     otomops_martiensseni.shp
     otomops_martiensseni.shx
     otonycteris_hemprichii.dbf
     otonycteris_hemprichii.shp
     otonycteris_hemprichii.shx
     paratriaenops_auritus.dbf
     paratriaenops_auritus.shp
     paratriaenops_auritus.shx
     paratriaenops_furculus.dbf
     paratriaenops_furculus.shp
     paratriaenops_furculus.shx
     paratriaenops_pauliani.dbf
     paratriaenops_pauliani.shp
     paratriaenops_pauliani.shx
     paremballonura_atrata.dbf
     paremballonura_atrata.shp
     paremballonura_atrata.shx
     paremballonura_tiavato.dbf
     paremballonura_tiavato.shp
     paremballonura_tiavato.shx
     pipistrellus_aero.dbf
     pipistrellus_aero.shp
     pipistrellus_aero.shx
     pipistrellus_deserti.dbf
     pipistrellus_deserti.shp
     pipistrellus_deserti.shx
     pipistrellus_grandidieri.dbf
     pipistrellus_grandidieri.shp
     pipistrellus_grandidieri.shx
     pipistrellus_hesperidus_hesperidus.dbf
     pipistrellus_hesperidus_hesperidus.shp
     pipistrellus_hesperidus_hesperidus.shx
     pipistrellus_hesperidus.dbf
     pipistrellus_hesperidus.shp
     pipistrellus_hesperidus.shx
     pipistrellus_inexspectatus.dbf
     pipistrellus_inexspectatus.shp
     pipistrellus_inexspectatus.shx
     pipistrellus_kuhlii.dbf
     pipistrellus_kuhlii.shp
     pipistrellus_kuhlii.shx
     pipistrellus_maderensis.dbf
     pipistrellus_maderensis.shp
     pipistrellus_maderensis.shx
     pipistrellus_nanulus.dbf
     pipistrellus_nanulus.shp
     pipistrellus_nanulus.shx
     pipistrellus_permixtus.dbf
     pipistrellus_permixtus.shp
     pipistrellus_permixtus.shx
     pipistrellus_pipistrellus.dbf
     pipistrellus_pipistrellus.shp
     pipistrellus_pipistrellus.shx
     pipistrellus_raceyi.dbf
     pipistrellus_raceyi.shp
     pipistrellus_raceyi.shx
     pipistrellus_rueppellii_fuscipes.dbf
     pipistrellus_rueppellii_fuscipes.shp
     pipistrellus_rueppellii_fuscipes.shx
     pipistrellus_rueppellii_pulcher.dbf
     pipistrellus_rueppellii_pulcher.shp
     pipistrellus_rueppellii_pulcher.shx
     pipistrellus_rueppellii_rueppellii.dbf
     pipistrellus_rueppellii_rueppellii.shp
     pipistrellus_rueppellii_rueppellii.shx
     pipistrellus_rueppellii_senegalensis.dbf
     pipistrellus_rueppellii_senegalensis.shp
     pipistrellus_rueppellii_senegalensis.shx
     pipistrellus_rueppellii_vernayi.dbf
     pipistrellus_rueppellii_vernayi.shp
     pipistrellus_rueppellii_vernayi.shx
     pipistrellus_rueppellii.dbf
     pipistrellus_rueppellii.shp
     pipistrellus_rueppellii.shx
     pipistrellus_rusticus.dbf
     pipistrellus_rusticus.shp
     pipistrellus_rusticus.shx
     pipistrellus.dbf
     pipistrellus.shp
     pipistrellus.shx
     platymops_setiger_macmillani.dbf
     platymops_setiger_macmillani.shp
     platymops_setiger_macmillani.shx
     platymops_setiger_setiger.dbf
     platymops_setiger_setiger.shp
     platymops_setiger_setiger.shx
     platymops_setiger.dbf
     platymops_setiger.shp
     platymops_setiger.shx
     plecotus_balensis.dbf
     plecotus_balensis.shp
     plecotus_balensis.shx
     plecotus_christii.dbf
     plecotus_christii.shp
     plecotus_christii.shx
     plecotus_gaisleri.dbf
     plecotus_gaisleri.shp
     plecotus_gaisleri.shx
     plecotus_teneriffae.dbf
     plecotus_teneriffae.shp
     plecotus_teneriffae.shx
     plecotus.dbf
     plecotus.shp
     plecotus.shx
     plerotes_anchietae.dbf
     plerotes_anchietae.shp
     plerotes_anchietae.shx
     pteropodidae.dbf
     pteropodidae.shp
     pteropodidae.shx
     pteropodinae.dbf
     pteropodinae.shp
     pteropodinae.shx
     pteropus_aldabrensis.dbf
     pteropus_aldabrensis.shp
     pteropus_aldabrensis.shx
     pteropus_livingstonii.dbf
     pteropus_livingstonii.shp
     pteropus_livingstonii.shx
     pteropus_niger.dbf
     pteropus_niger.shp
     pteropus_niger.shx
     pteropus_rodricensis.dbf
     pteropus_rodricensis.shp
     pteropus_rodricensis.shx
     pteropus_rufus.dbf
     pteropus_rufus.shp
     pteropus_rufus.shx
     pteropus_seychellensis.dbf
     pteropus_seychellensis.shp
     pteropus_seychellensis.shx
     pteropus_subniger.dbf
     pteropus_subniger.shp
     pteropus_subniger.shx
     pteropus_voeltzkowi.dbf
     pteropus_voeltzkowi.shp
     pteropus_voeltzkowi.shx
     pteropus.dbf
     pteropus.shp
     pteropus.shx
     rhinolophidae.dbf
     rhinolophidae.shp
     rhinolophidae.shx
     rhinolophus_adami.dbf
     rhinolophus_adami.shp
     rhinolophus_adami.shx
     rhinolophus_alcyone.dbf
     rhinolophus_alcyone.shp
     rhinolophus_alcyone.shx
     rhinolophus_blasii.dbf
     rhinolophus_blasii.shp
     rhinolophus_blasii.shx
     rhinolophus_capensis.dbf
     rhinolophus_capensis.shp
     rhinolophus_capensis.shx
     rhinolophus_clivosus.dbf
     rhinolophus_clivosus.shp
     rhinolophus_clivosus.shx
     rhinolophus_cohenae.dbf
     rhinolophus_cohenae.shp
     rhinolophus_cohenae.shx
     rhinolophus_darlingi.dbf
     rhinolophus_darlingi.shp
     rhinolophus_darlingi.shx
     rhinolophus_deckenii.dbf
     rhinolophus_deckenii.shp
     rhinolophus_deckenii.shx
     rhinolophus_denti.dbf
     rhinolophus_denti.shp
     rhinolophus_denti.shx
     rhinolophus_eloquens.dbf
     rhinolophus_eloquens.shp
     rhinolophus_eloquens.shx
     rhinolophus_euryale.dbf
     rhinolophus_euryale.shp
     rhinolophus_euryale.shx
     rhinolophus_ferrumequinum.dbf
     rhinolophus_ferrumequinum.shp
     rhinolophus_ferrumequinum.shx
     rhinolophus_fumigatus.dbf
     rhinolophus_fumigatus.shp
     rhinolophus_fumigatus.shx
     rhinolophus_guineensis.dbf
     rhinolophus_guineensis.shp
     rhinolophus_guineensis.shx
     rhinolophus_hildebrandtii.dbf
     rhinolophus_hildebrandtii.shp
     rhinolophus_hildebrandtii.shx
     rhinolophus_hilli.dbf
     rhinolophus_hilli.shp
     rhinolophus_hilli.shx
     rhinolophus_hillorum.dbf
     rhinolophus_hillorum.shp
     rhinolophus_hillorum.shx
     rhinolophus_hipposideros.dbf
     rhinolophus_hipposideros.shp
     rhinolophus_hipposideros.shx
     rhinolophus_landeri.dbf
     rhinolophus_landeri.shp
     rhinolophus_landeri.shx
     rhinolophus_mabuensis.dbf
     rhinolophus_mabuensis.shp
     rhinolophus_mabuensis.shx
     rhinolophus_maclaudi.dbf
     rhinolophus_maclaudi.shp
     rhinolophus_maclaudi.shx
     rhinolophus_maendeleo.dbf
     rhinolophus_maendeleo.shp
     rhinolophus_maendeleo.shx
     rhinolophus_mehelyi.dbf
     rhinolophus_mehelyi.shp
     rhinolophus_mehelyi.shx
     rhinolophus_mossambicus.dbf
     rhinolophus_mossambicus.shp
     rhinolophus_mossambicus.shx
     rhinolophus_ruwenzorii.dbf
     rhinolophus_ruwenzorii.shp
     rhinolophus_ruwenzorii.shx
     rhinolophus_sakejiensis.dbf
     rhinolophus_sakejiensis.shp
     rhinolophus_sakejiensis.shx
     rhinolophus_silvestris.dbf
     rhinolophus_silvestris.shp
     rhinolophus_silvestris.shx
     rhinolophus_simulator.dbf
     rhinolophus_simulator.shp
     rhinolophus_simulator.shx
     rhinolophus_smithersi.dbf
     rhinolophus_smithersi.shp
     rhinolophus_smithersi.shx
     rhinolophus_swinnyi.dbf
     rhinolophus_swinnyi.shp
     rhinolophus_swinnyi.shx
     rhinolophus_ziama.dbf
     rhinolophus_ziama.shp
     rhinolophus_ziama.shx
     rhinolophus.dbf
     rhinolophus.shp
     rhinolophus.shx
     rhinopoma_cystops.dbf
     rhinopoma_cystops.shp
     rhinopoma_cystops.shx
     rhinopoma_macinnesi.dbf
     rhinopoma_macinnesi.shp
     rhinopoma_macinnesi.shx
     rhinopoma_microphyllum.dbf
     rhinopoma_microphyllum.shp
     rhinopoma_microphyllum.shx
     rousettus_aegyptiacus.dbf
     rousettus_aegyptiacus.shp
     rousettus_aegyptiacus.shx
     rousettus_lanosus.dbf
     rousettus_lanosus.shp
     rousettus_lanosus.shx
     rousettus_madagascariensis.dbf
     rousettus_madagascariensis.shp
     rousettus_madagascariensis.shx
     rousettus_obliviosus.dbf
     rousettus_obliviosus.shp
     rousettus_obliviosus.shx
     rousettus.dbf
     rousettus.shp
     rousettus.shx
     saccolaimus_peli.dbf
     saccolaimus_peli.shp
     saccolaimus_peli.shx
     sauromys_petrophilus_erongensis.dbf
     sauromys_petrophilus_erongensis.shp
     sauromys_petrophilus_erongensis.shx
     sauromys_petrophilus_haagneri.dbf
     sauromys_petrophilus_haagneri.shp
     sauromys_petrophilus_haagneri.shx
     sauromys_petrophilus_petrophilus.dbf
     sauromys_petrophilus_petrophilus.shp
     sauromys_petrophilus_petrophilus.shx
     sauromys_petrophilus_umbratus.dbf
     sauromys_petrophilus_umbratus.shp
     sauromys_petrophilus_umbratus.shx
     sauromys_petrophilus.dbf
     sauromys_petrophilus.shp
     sauromys_petrophilus.shx
     scotoecus_albigula.dbf
     scotoecus_albigula.shp
     scotoecus_albigula.shx
     scotoecus_albofuscus.dbf
     scotoecus_albofuscus.shp
     scotoecus_albofuscus.shx
     scotoecus_hindei.dbf
     scotoecus_hindei.shp
     scotoecus_hindei.shx
     scotoecus_hirundo.dbf
     scotoecus_hirundo.shp
     scotoecus_hirundo.shx
     scotoecus.dbf
     scotoecus.shp
     scotoecus.shx
     scotonycteris_ophiodon.dbf
     scotonycteris_ophiodon.shp
     scotonycteris_ophiodon.shx
     scotonycteris_zenkeri.dbf
     scotonycteris_zenkeri.shp
     scotonycteris_zenkeri.shx
     scotophilus_borbonicus.dbf
     scotophilus_borbonicus.shp
     scotophilus_borbonicus.shx
     scotophilus_dinganii.dbf
     scotophilus_dinganii.shp
     scotophilus_dinganii.shx
     scotophilus_leucogaster.dbf
     scotophilus_leucogaster.shp
     scotophilus_leucogaster.shx
     scotophilus_marovaza.dbf
     scotophilus_marovaza.shp
     scotophilus_marovaza.shx
     scotophilus_nigrita.dbf
     scotophilus_nigrita.shp
     scotophilus_nigrita.shx
     scotophilus_nucella.dbf
     scotophilus_nucella.shp
     scotophilus_nucella.shx
     scotophilus_nux.dbf
     scotophilus_nux.shp
     scotophilus_nux.shx
     scotophilus_robustus.dbf
     scotophilus_robustus.shp
     scotophilus_robustus.shx
     scotophilus_tandrefana.dbf
     scotophilus_tandrefana.shp
     scotophilus_tandrefana.shx
     scotophilus_viridis.dbf
     scotophilus_viridis.shp
     scotophilus_viridis.shx
     scotophilus.dbf
     scotophilus.shp
     scotophilus.shx
     tadarida_aegyptiaca_aegyptiaca.dbf
     tadarida_aegyptiaca_aegyptiaca.shp
     tadarida_aegyptiaca_aegyptiaca.shx
     tadarida_aegyptiaca_bocagei.dbf
     tadarida_aegyptiaca_bocagei.shp
     tadarida_aegyptiaca_bocagei.shx
     tadarida_aegyptiaca.dbf
     tadarida_aegyptiaca.shp
     tadarida_aegyptiaca.shx
     tadarida_fulminans.dbf
     tadarida_fulminans.shp
     tadarida_fulminans.shx
     tadarida_lobata.dbf
     tadarida_lobata.shp
     tadarida_lobata.shx
     tadarida_teniotis.dbf
     tadarida_teniotis.shp
     tadarida_teniotis.shx
     tadarida_ventralis.dbf
     tadarida_ventralis.shp
     tadarida_ventralis.shx
     tadarida.dbf
     tadarida.shp
     tadarida.shx
     taphozous_hamiltoni.dbf
     taphozous_hamiltoni.shp
     taphozous_hamiltoni.shx
     taphozous_hildegardeae.dbf
     taphozous_hildegardeae.shp
     taphozous_hildegardeae.shx
     taphozous_mauritianus.dbf
     taphozous_mauritianus.shp
     taphozous_mauritianus.shx
     taphozous_nudiventris.dbf
     taphozous_nudiventris.shp
     taphozous_nudiventris.shx
     taphozous_perforatus_perforatus.dbf
     taphozous_perforatus_perforatus.shp
     taphozous_perforatus_perforatus.shx
     taphozous_perforatus_sudani.dbf
     taphozous_perforatus_sudani.shp
     taphozous_perforatus_sudani.shx
     taphozous_perforatus.dbf
     taphozous_perforatus.shp
     taphozous_perforatus.shx
     taphozous.dbf
     taphozous.shp
     taphozous.shx
     triaenops_afer.dbf
     triaenops_afer.shp
     triaenops_afer.shx
     triaenops_goodmani.dbf
     triaenops_goodmani.shp
     triaenops_goodmani.shx
     triaenops_menamena.dbf
     triaenops_menamena.shp
     triaenops_menamena.shx
     triaenops.dbf
     triaenops.shp
     triaenops.shx
     vespertilionidae.dbf
     vespertilionidae.shp
     vespertilionidae.shx
     vespertilioninae.dbf
     vespertilioninae.shp
     vespertilioninae.shx
     vespertilionoidea.dbf
     vespertilionoidea.shp
     vespertilionoidea.shx')

x <- strsplit(X, split="\n")

x<- as.data.frame(x)
colnames(x) <- c("species")
x2 <- x %>%
  filter(grepl('.dbf', species))

1104/368 == 3

x3 <- x2 %>%
  mutate(species = gsub("_", " ", species)) %>%
  mutate(species = gsub(".dbf", "", species))

write.csv(x3, file= 'data/african bats')
